[build]
  command = "pnpm run build"
  publish = "build/client"

[[redirects]]
  from = "/team"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*"
  to = "/__spa-fallback.html"
  status = 200
